<nav>
  <a href="account.php">Account</a> |
  <a href="add_to_cart.php">Add to Cart</a> |
  <a href="admin.php">Admin</a> |
  <a href="cart.php">Cart</a> |
  <a href="contact.php">Contact</a> |
  <a href="get_cart_count.php">Get Cart Count</a> |
  <a href="index.php">Index</a> |
  <a href="login.php">Login</a> |
  <a href="order_confirmation.php">Order Confirmation</a> |
  <a href="payment.php">payment</a> |
  <a href="process_payment.php">Process Payment</a> |
  <a href="productdetails.php">Product Details</a> |
  <a href="products.php">Products</a> |
  <a href="update_cart.php">Update cart</a> |


</nav>
